on:
  pull_request:
    branches:
      - develop
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo The PR was merged

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install Prettier
        run: npm install prettier

      - name: Lint code with Prettier
        run: prettier --write

      - name: Install Google Apps Script CLI
        run: npm install -g @google/clasp

      - name: Decrypt clasp credentials
        run: |
          gpg \
            --quiet --batch --yes --decrypt --passphrase="${{ secrets.CLASP_SECRET_PSW }}" \
            --output $HOME/.clasprc.json .clasprc.json.gpg

      - name: Push to Google Apps Script
        run: npx clasp push -f

      - name: Deploy to Google Apps Script
        run: npx clasp deploy -i AKfycby0QMWsktI7z5kB0jYsRn1DGFXGcegnLu3muPVEe6CnVoyM8jRYZf2mbUSnM3mwSijT -d \"Development\" -V dev
